name = "ToonFormat"
uuid = "7e1e1c4e-8b9a-4f3d-9c1e-2f3a4b5c6d7e"
version = "0.1.1"
authors = ["TOON Format Organization"]

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Aqua = "0.8"
JSON3 = "1"
JSONSchema = "1"
LazyArtifacts = "1"
OrderedCollections = "1"
Printf = "1"
Test = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JSON3", "JSONSchema", "LazyArtifacts", "Test"]
